const express = require("express")
const app = express()
require("dotenv").config()
require("../../database/connection")
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const adminRoutes = require("../../routes/admin.routes")
app.use("/api/admin",adminRoutes) 
const productRoutes = require("../../routes/product.routes")
app.use("/api/product",productRoutes)
const categoryRoutes = require("../../routes/category.routes")
app.use("/api/category",categoryRoutes)
app.get("*", (req,res)=> res.send( {error:"invalid url"} ) )
module.exports=app
